
message(STATUS "Looking for glm ...")

FIND_PATH(GLM_INCLUDE_DIR 
  NAMES glm.hpp
  HINTS ${GLM_HOME}
  PATH_SUFFIXES glm
#  PATHS include
)


message(STATUS "${GLM_INCLUDE_DIR}")

SET(GLM_FOUND "NO")
IF(GLM_INCLUDE_DIR)
  SET(GLM_FOUND "YES")
ENDIF(GLM_INCLUDE_DIR)

