
message(STATUS "Looking for ShaderConductor ...")

FIND_PATH(SHADERCONDUCTOR_INCLUDE_DIR 
  NAMES ShaderConductor.hpp
  HINTS ${SHADERCONDUCTOR_HOME}
  PATH_SUFFIXES include
#  PATHS include
)

FIND_LIBRARY(SHADERCONDUCTOR_LIBRARY_TEMP
  NAMES ShaderConductor ShaderConductor.a
  HINTS ${SHADERCONDUCTOR_HOME}
  PATH_SUFFIXES ${SHADERCONDUCTOR_LIB_SUFFIXES}
#  PATHS .
)

FIND_FILE(SHADERCONDUCTOR_BINARY
  NAMES "ShaderConductor.dll" "libShaderConductor.so" "ShaderConductor.dylib"
  HINTS ${SHADERCONDUCTOR_HOME}
  PATH_SUFFIXES ${SHADERCONDUCTOR_LIB_SUFFIXES}
)

message(STATUS "${SHADERCONDUCTOR_INCLUDE_DIR}")
message(STATUS "${SHADERCONDUCTOR_LIBRARY_TEMP}")
message(STATUS "${SHADERCONDUCTOR_BINARY}")

SET(SHADERCONDUCTOR_FOUND "NO")
IF(SHADERCONDUCTOR_LIBRARY_TEMP)
  # Set the final string here so the GUI reflects the final state.
  SET(SHADERCONDUCTOR_LIBRARY ${SHADERCONDUCTOR_LIBRARY_TEMP} CACHE STRING "Where the ShaderConductor Library can be found")
  # Set the temp variable to INTERNAL so it is not seen in the CMake GUI
  SET(SHADERCONDUCTOR_LIBRARY_TEMP "${SHADERCONDUCTOR_LIBRARY_TEMP}" CACHE INTERNAL "")

  SET(SHADERCONDUCTOR_FOUND "YES")
ENDIF(SHADERCONDUCTOR_LIBRARY_TEMP)

