
message(STATUS "Looking for rapidjson ...")

FIND_PATH(RAPIDJSON_INCLUDE_DIR 
  NAMES rapidjson.h
  HINTS ${RAPIDJSON_HOME}
  PATH_SUFFIXES .
#  PATHS include
)

message(STATUS "${RAPIDJSON_INCLUDE_DIR}")

SET(RAPIDJSON_FOUND "NO")
IF(RAPIDJSON_INCLUDE_DIR)
  SET(SHADERCONDUCTOR_FOUND "YES")
ENDIF(RAPIDJSON_INCLUDE_DIR)

